var url = 'VjFV2IxVXdNVWhVYTJ4VlZrWndUbHBXVW5OTmJHdDNXa1prYTFaWWFEQlZNalZEV1ZVeGNWSnFTbGhoTWxKWVdYcENOR1JHVW5WV2F6Rk9ZVEZ2ZWxkV1drNU9WMUY0WWtab1UySnVRazVVVkVaeVpERlNSVk5yT1dsTlYzaGFWbFpvWVZkck1YRmlSRUphVFVkUk1GbHJaRk5UUjBwSlYyMXNhV0Y2UVRVPQ==';
var apikey = 'VkdU2NrMUdjRVZhTTJST1VrVkZlRlJWWkZwa01EVkZVMVJLVUZKSGMzaFhiR1JUWVVVNVJWWnRNVkJXUm5CdlZHdGtUbVZWT1ZoV1dGWk9Vako0U0ZacVJtOVVWVGxJV2toYVdrMUVSa3hVVlZaVFpVWmtVbEJVTUQwPQ==';
var model = 'GLM-4.7-Flash';

var webSearchUrl = 'VjFV2IxVXdNVWhVYTJ4VlZrWndUbHBXVW5OaU1XdDNXa2hLYTFZeFNrbFZiWEJMWVVaWmVscDZSbFZTZWtaUVdrY3hTMVpGT1ZsalIwWlhUVVp2TVZZeFVrdGliRUpTVUZRd1BRPT0=';
var webSearchApiKey = 'V2tb1lXTXlWbFJOVjNSaFYwWnNNRlJVUmxOVVJsWllaRVJPVFZaNmF6QmFSVnBMVkRKV1ZsTlVSbGRXV0dONFZqQmtORll3T1ZoYVJuQnJUVEpTTUZkcVNsZE5SMUpIVVZod2FGWldjRE5aYTJRMFkyc3dlRlJ1U2xWV01sSjNWRlZTVTFZeVVtNVFWREE5';

// 使用示例
// const messages = [{
//     role: 'user',
//     content: '你好'
// }];
